name: Release and Publish

on:
  push:
    branches: [master]

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node

      - uses: actions/checkout@v5
        if: ${{ steps.release.outputs.release_created }}

      - uses: pnpm/action-setup@v5
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm
          registry-url: https://npm.pkg.github.com
          scope: "@icqqjs"
        if: ${{ steps.release.outputs.release_created }}

      - name: Install and build
        run: pnpm install --frozen-lockfile && pnpm build
        env:
          NODE_AUTH_TOKEN: ${{secrets.INSTALL_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to GitHub Packages
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
